import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

// Importing package.json instead would pull it outside rootDir and reshape the
// build output; reading it at runtime is impossible on Workers.
const packageDir = process.cwd();
const target = path.join(packageDir, "src", "version.ts");

const { name, version } = JSON.parse(
  readFileSync(path.join(packageDir, "package.json"), "utf8"),
);

const contents = `// Generated by scripts/generate-version.mjs - do not edit.
export const PACKAGE_NAME = "${name}";

export const PACKAGE_VERSION = "${version}";
`;

const current = (() => {
  try {
    return readFileSync(target, "utf8");
  } catch {
    return null;
  }
})();

if (current !== contents) {
  writeFileSync(target, contents);
  console.log(`generate-version: ${name}@${version}`);
}
