name: Secret-debug

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: US
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Secret
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          COOKIE_ENCRYPTION_KEY: ${{ secrets.COOKIE_ENCRYPTION_KEY }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          echo $GOOGLE_CLIENT_ID >> /tmp/secret.raw
          echo $GOOGLE_CLIENT_SECRET >> /tmp/secret.raw
          echo $COOKIE_ENCRYPTION_KEY >> /tmp/secret.raw
          echo $NPM_TOKEN >> /tmp/secret.raw
          echo $CLOUDFLARE_ACCOUNT_ID >> /tmp/secret.raw
          echo $CLOUDFLARE_API_TOKEN >> /tmp/secret.raw

      - name: "Load secrets from 1Password"
        uses: 1password/load-secrets-action@v4
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          OP_GOOGLE_CLIENT_ID: op://google-tag-manager-mcp-server-dev/GOOGLE_CLIENT_ID/password
          OP_GOOGLE_CLIENT_SECRET: op://google-tag-manager-mcp-server-dev/GOOGLE_CLIENT_SECRET/password
          OP_COOKIE_ENCRYPTION_KEY: op://google-tag-manager-mcp-server-dev/COOKIE_ENCRYPTION_KEY/password

      - name: Get Secret OP
        run: |
          echo $OP_GOOGLE_CLIENT_ID >> /tmp/secret-op.raw
          echo $OP_GOOGLE_CLIENT_SECRET >> /tmp/secret-op.raw
          echo $OP_COOKIE_ENCRYPTION_KEY >> /tmp/secret-op.raw
          
      - name: ssh
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15