on:
  push:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm ci
      - run: npm run prepublish

      - name: "Load secrets from 1Password"
        uses: 1password/load-secrets-action@v4
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          NPM_TOKEN: op://google-tag-manager-mcp-server/NPM_TOKEN/password

      - uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ env.NPM_TOKEN }}
